#!/usr/bin/env python3

# seu código aqui

def readline(socket):
	ret = ''
	while True:
		c = conexao.recv(1)
		print(ret)

		if c == b'\\':
			d = conexao.recv(1)
			if d == b'n':
				e = conexao.recv(1)
				if e == b'':
					break
		elif c == b'\n':
			break

		else:
			ret += str(c.decode("utf-8"))

	print(ret)


import socket

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
s.bind(('', 7000))
s.listen(5)

conexao, endereco = s.accept()
print("Connected by", endereco)
while True:	
	data = readline(s)
	conexao.send(b"/error\n")
	if not data: break


