#!/usr/bin/env python3

# seu código aqui

# def readline(socket):
# 	line = bytearray()
# 	while 1:
# 		data = conexao.recv(1)
# 		if data == b'\n':
# 			return line 
# 		else:
# 			line.extend(data)

def readline(socket):
	line = bytearray()
	while 1:
		print(gerador(socket, line))


def gerador(socket, line):
	buffer = conexao.recv(2048)
	buffering = True
	while buffering:
		if '\n' in buffer:
			(line, buffer) = buffer.split("\n", 1)
			yield line + "\n"
		else:
			more = socket.recv(2048)
			if not more:
				buffering = False
			else:
				buffer += more
	if buffer:
		yield buffer
		print(buffer)

import socket

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
s.bind(('', 7000))
s.listen(5)

conexao, endereco = s.accept()
print("Connected by", endereco)
while True:	
	data = readline(s)
	conexao.send(b"/error\n")
	if not data: break


